version: '2'

services:
  backend:
    image: heavymatill/band-mevn-backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend/:/usr/src/app
    links:
      - mongo_db
    environment:
      - MONGODB_URI=mongodb://mongo_db:27017/band_db

  mongo_db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - 'mongo_data:/data/db'

  frontend:
    image: heavymatill/band-mevn-frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/usr/src/app
    links:
      - backend
    environment:
      - VUE_APP_BACKEND_URI=https://semfshow.herokuapp.com
      - VUE_APP_BACKEND_URI_notworking=http://backend:4000
volumes:
  mongo_data: